# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mv_FHN_ <- function(mat, vec) {
    .Call(`_SplittingStochasticFHN_mv_FHN_`, mat, vec)
}

linSDE_FHN_Cpp_ <- function(vec, dm, cm, randvec) {
    .Call(`_SplittingStochasticFHN_linSDE_FHN_Cpp_`, vec, dm, cm, randvec)
}

nonlinODE_FHN_Cpp_ <- function(vec, h, eps, beta) {
    .Call(`_SplittingStochasticFHN_nonlinODE_FHN_Cpp_`, vec, h, eps, beta)
}

FHN_Strang_Cpp_ <- function(grid_i, h_i, startv_i, dm_i, cm_i, eps_i, beta_i) {
    .Call(`_SplittingStochasticFHN_FHN_Strang_Cpp_`, grid_i, h_i, startv_i, dm_i, cm_i, eps_i, beta_i)
}

