# --- SLURM CONFIG ---
# importance: medium
# sbatch_args:
#   partition: gpu-rtx6000
#   gpus: "rtx_pro_6000_blackwell:1"
#   cpus-per-gpu: 1
#   mem: 6GB
# jobs:
#   fast:
#     sbatch_args:
#       job-name: "measles speed comparison (pypomp fast)"
#       output: "results/logs/slurm-fast-%j.out"
#     env:
#       MODEL_TYPE: "fast"
#   jax:
#     sbatch_args:
#       job-name: "measles speed comparison (pypomp jax)"
#       output: "results/logs/slurm-jax-%j.out"
#     env:
#       MODEL_TYPE: "jax"
# run_levels:
#   1:
#     sbatch_args: { time: "00:04:00" }
#   2:
#     sbatch_args: { time: "00:20:00" }
#   3:
#     sbatch_args: { time: "01:00:00" }
#   4:
#     sbatch_args: { time: "02:00:00" }
# --- END SLURM CONFIG ---

import os
import pickle
import time

import jax
import model_001b_jax
import numpy as np
import pandas as pd
import pypomp as pp
from pypomp.core.par_trans import ParTrans
from pypomp.core.pomp import Pomp
from pypomp.models.measles.measlesPomp import UKMeasles

print("Available JAX Devices:", jax.devices())

MAIN_SEED = 594709947
key = jax.random.key(MAIN_SEED)
np.random.seed(MAIN_SEED)

RUN_LEVEL = int(os.environ.get("RUN_LEVEL", "1"))
NP_FITR = (2, 500, 5000, 5000)[RUN_LEVEL - 1]
NFITR = (2, 10, 100, 100)[RUN_LEVEL - 1]
NREPS_FITR = (2, 3, 36, 36)[RUN_LEVEL - 1]

MODEL_TYPE = os.environ.get("MODEL_TYPE", "fast").lower()
assert MODEL_TYPE in ["fast", "jax"], f"Invalid MODEL_TYPE: {MODEL_TYPE}"

print(f"Running at level {RUN_LEVEL}")
print(f"MODEL_TYPE: {MODEL_TYPE}")

# Load starting parameters generated by R, sliced to match replication count
starting_params_df = pd.read_csv("starting_parameters.csv").iloc[:NREPS_FITR]
starting_parameters = pp.PompParameters(starting_params_df.to_dict(orient="records"))

# London unit
unit_name = "London"

if MODEL_TYPE == "fast":
    # Build Scenario A (Default fast pypomp)
    model_obj = UKMeasles.Pomp(
        unit=[unit_name],
        theta=starting_parameters,
        model="001b",
        clean=False,
    )
else:
    # Build Scenario B (JAX samplers pypomp)
    base_pomp = UKMeasles.Pomp(
        unit=[unit_name],
        theta=starting_parameters,
        model="001b",
        clean=False,
    )
    model_obj = Pomp(
        ys=base_pomp.ys,
        theta=starting_parameters,
        covars=base_pomp.covars,
        t0=base_pomp.t0,
        nstep=None,
        dt=1 / 365.25,
        accumvars=model_001b_jax.accumvars,
        statenames=model_001b_jax.statenames,
        rinit=model_001b_jax.rinit,
        rproc=model_001b_jax.rproc,
        dmeas=model_001b_jax.dmeas,
        rmeas=model_001b_jax.rmeas,
        par_trans=ParTrans(
            to_est=model_001b_jax.to_est, from_est=model_001b_jax.from_est
        ),
    )

# Define random walk SDs matching R exactly
DEFAULT_SD = 0.02
DEFAULT_IVP_SD = DEFAULT_SD * 12
RW_SD = pp.RWSigma(
    sigmas={
        "R0": DEFAULT_SD,
        "sigma": DEFAULT_SD,
        "gamma": DEFAULT_SD * 0.5,
        "iota": DEFAULT_SD,
        "rho": DEFAULT_SD * 0.5,
        "sigmaSE": DEFAULT_SD,
        "psi": DEFAULT_SD * 0.25,
        "cohort": DEFAULT_SD * 0.5,
        "amplitude": DEFAULT_SD * 0.5,
        "S_0": DEFAULT_IVP_SD,
        "E_0": DEFAULT_IVP_SD,
        "I_0": DEFAULT_IVP_SD,
        "R_0": DEFAULT_IVP_SD,
    },
    init_names=["S_0", "E_0", "I_0", "R_0"],
).geometric_cooling(a=0.5)

# --- RUN BENCHMARK ---
print(f"\n--- Running benchmark for: {MODEL_TYPE} ---")

# 1. Benchmark MIF
key, subkey = jax.random.split(key)
t_start = time.perf_counter()
model_obj.mif(J=NP_FITR, M=NFITR, key=subkey, rw_sd=RW_SD)
t_mif = time.perf_counter() - t_start
print(f"MIF completed in {t_mif:.2f} seconds.")

# 2. Benchmark Pfilter
key, subkey = jax.random.split(key)
t_start = time.perf_counter()
model_obj.pfilter(J=NP_FITR, reps=36, key=subkey)
t_pfilter = time.perf_counter() - t_start
print(f"Pfilter completed in {t_pfilter:.2f} seconds.")

# Extract results
traces_df = model_obj.traces()
results_df = model_obj.results()

results_to_save = {
    "mif_time": t_mif,
    "pfilter_time": t_pfilter,
    "traces": traces_df,
    "results": results_df,
}

# Save results
os.makedirs("results", exist_ok=True)
output_path = f"results/pypomp_speed_results_{MODEL_TYPE}.pkl"
with open(output_path, "wb") as f:
    pickle.dump(results_to_save, f)

print(f"\npypomp {MODEL_TYPE} benchmark complete. Saved to {output_path}")
