// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mv_FHN_
NumericVector mv_FHN_(NumericMatrix mat, NumericVector vec);
RcppExport SEXP _SplittingStochasticFHN_mv_FHN_(SEXP matSEXP, SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(mv_FHN_(mat, vec));
    return rcpp_result_gen;
END_RCPP
}
// linSDE_FHN_Cpp_
NumericVector linSDE_FHN_Cpp_(NumericVector vec, NumericMatrix dm, NumericMatrix cm, NumericVector randvec);
RcppExport SEXP _SplittingStochasticFHN_linSDE_FHN_Cpp_(SEXP vecSEXP, SEXP dmSEXP, SEXP cmSEXP, SEXP randvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cm(cmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type randvec(randvecSEXP);
    rcpp_result_gen = Rcpp::wrap(linSDE_FHN_Cpp_(vec, dm, cm, randvec));
    return rcpp_result_gen;
END_RCPP
}
// nonlinODE_FHN_Cpp_
NumericVector nonlinODE_FHN_Cpp_(NumericVector vec, double h, double eps, double beta);
RcppExport SEXP _SplittingStochasticFHN_nonlinODE_FHN_Cpp_(SEXP vecSEXP, SEXP hSEXP, SEXP epsSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(nonlinODE_FHN_Cpp_(vec, h, eps, beta));
    return rcpp_result_gen;
END_RCPP
}
// FHN_Strang_Cpp_
NumericMatrix FHN_Strang_Cpp_(NumericVector grid_i, double h_i, NumericVector startv_i, NumericMatrix dm_i, NumericMatrix cm_i, double eps_i, double beta_i);
RcppExport SEXP _SplittingStochasticFHN_FHN_Strang_Cpp_(SEXP grid_iSEXP, SEXP h_iSEXP, SEXP startv_iSEXP, SEXP dm_iSEXP, SEXP cm_iSEXP, SEXP eps_iSEXP, SEXP beta_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type grid_i(grid_iSEXP);
    Rcpp::traits::input_parameter< double >::type h_i(h_iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type startv_i(startv_iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dm_i(dm_iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cm_i(cm_iSEXP);
    Rcpp::traits::input_parameter< double >::type eps_i(eps_iSEXP);
    Rcpp::traits::input_parameter< double >::type beta_i(beta_iSEXP);
    rcpp_result_gen = Rcpp::wrap(FHN_Strang_Cpp_(grid_i, h_i, startv_i, dm_i, cm_i, eps_i, beta_i));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SplittingStochasticFHN_mv_FHN_", (DL_FUNC) &_SplittingStochasticFHN_mv_FHN_, 2},
    {"_SplittingStochasticFHN_linSDE_FHN_Cpp_", (DL_FUNC) &_SplittingStochasticFHN_linSDE_FHN_Cpp_, 4},
    {"_SplittingStochasticFHN_nonlinODE_FHN_Cpp_", (DL_FUNC) &_SplittingStochasticFHN_nonlinODE_FHN_Cpp_, 4},
    {"_SplittingStochasticFHN_FHN_Strang_Cpp_", (DL_FUNC) &_SplittingStochasticFHN_FHN_Strang_Cpp_, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_SplittingStochasticFHN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
