"""Shared definition of the SIR Bayesian benchmark for pypomp.

Import this from a kind directory (reference/, pmcmc/, abc/):

    import model

Paths below are relative to the kind directory, since the test runner cd's into
the directory of the script it is running. All kinds sit at the same depth, so
one path works for each.

The dataset is generated by R (see model.R) and read here, rather than letting
pypomp's ``sir()`` simulate its own. Both constructors simulate at build time
from different RNGs, so one side has to be the generator of record or nothing
downstream is comparable.
"""

import jax
import jax.numpy as jnp
import numpy as np
import pandas as pd
import pypomp as pp
import xarray as xr
from pypomp.core.par_trans import ParTrans
from pypomp.core.parameters import PompParameters
from pypomp.models.sir import (
    STATENAMES,
    dmeas,
    from_est,
    precompute_bspline_covars,
    rinit,
    rmeas,
    rproc,
    to_est,
)
from pypomp.types import ParamDict

MAIN_SEED = 3141593

#: The two estimated parameters. Everything else is fixed at its true value.
FREE = ("beta1", "rho")

#: Flat bounded priors, matching the Csnippet in model.R exactly.
#:
#: The width is set by what the grid reference can resolve, not by taste. A
#: level-1 scan of the likelihood surface puts the posterior sd near 11 for
#: beta1 and 0.019 for rho, so the box below spans roughly +/-9 posterior sd in
#: each direction: wide enough that the flat-prior truncation is irrelevant and
#: that chains started from the prior are genuinely dispersed, tight enough that
#: a 60x60 grid gives about three cells per posterior sd. An earlier, much wider
#: box gave barely one cell per sd, which is too coarse to serve as a reference.
PRIOR_BOX: dict[str, tuple[float, float]] = {
    "beta1": (300.0, 500.0),
    "rho": (0.45, 0.80),
}

#: Random-walk proposal scales, on the ESTIMATION scale -- log for beta1, logit
#: for rho, per pypomp.models.sir.to_est.
#:
#: This is measured, not assumed. pypomp's pmcmc runs the chain on the
#: transformed scale: an rw_sd of 0.05 moves beta1 by about +/-20 around 400
#: (= 400*exp(0.05)), while an rw_sd of 10 moves it not at all, because
#: 400*exp(+/-10) lands outside the prior box and is rejected every time.
#: dprior, the traces, and PompParameters are all on the natural scale; only the
#: proposal is transformed.
#:
#: Consequence: this is NOT interchangeable with the natural-scale rw.sd that
#: R's mvn_diag_rw takes. model.R carries the local-linearization image of these
#: numbers so the two kernels are comparably efficient -- but they are different
#: kernels, both valid, and only their stationary distributions are compared.
RW_SD: dict[str, float] = {"beta1": 0.02, "rho": 0.05}

DATA_PATH = "../data/sir_data.csv"
TRUE_PATH = "../data/true_theta.csv"
SCALE_PATH = "../data/probe_scale.csv"

T0 = 0.0
NSTEP = 20
ACCUMVARS = ("cases", "logw")


def load_data(path: str = DATA_PATH) -> pd.DataFrame:
    """The canonical dataset, indexed by observation time."""
    return pd.read_csv(path).set_index("time")


def true_theta(path: str = TRUE_PATH) -> dict[str, float]:
    """The simulating parameters, as written by model.R."""
    df = pd.read_csv(path)
    return dict(zip(df["parameter"], df["value"].astype(float)))


def sir_dprior(params: ParamDict) -> float:
    """Log-density of the flat box prior on ``beta1`` and ``rho``.

    Normalized inside the box and ``-inf`` outside, so proposals leaving the box
    are rejected.

    pypomp hands this function natural-scale values, the same contract as pomp's
    dprior Csnippet, which is what lets the two be written identically. Measured
    rather than assumed: with the box below, pmcmc reports a log_prior of exactly
    -log(hi_b - lo_b) - log(hi_r - lo_r) at the true theta, with no Jacobian term
    added. Note this is a *different* scale from the one the proposal works on --
    see the note on RW_SD above.
    """
    lo_b, hi_b = PRIOR_BOX["beta1"]
    lo_r, hi_r = PRIOR_BOX["rho"]
    inside = (
        (params["beta1"] > lo_b)
        & (params["beta1"] < hi_b)
        & (params["rho"] > lo_r)
        & (params["rho"] < hi_r)
    )
    log_dens = -jnp.log(hi_b - lo_b) - jnp.log(hi_r - lo_r)
    return jnp.where(inside, log_dens, -jnp.inf)


def params_from_frame(rows: pd.DataFrame) -> PompParameters:
    """A replicate-indexed PompParameters from one row per chain/grid point."""
    names = list(rows.columns)
    arr = np.expand_dims(rows.to_numpy(dtype=float), axis=1)  # (n, 1, p)
    da = xr.DataArray(
        arr,
        dims=["theta_idx", "unit", "parameter"],
        coords={
            "theta_idx": np.arange(len(rows)),
            "unit": ["shared"],
            "parameter": names,
        },
    )
    return PompParameters(da)


def theta_frame(n: int, overrides: dict[str, np.ndarray] | None = None) -> pd.DataFrame:
    """``n`` copies of the true parameter vector, with ``overrides`` applied."""
    base = true_theta()
    frame = pd.DataFrame([base] * n).reset_index(drop=True)
    for name, values in (overrides or {}).items():
        frame[name] = np.asarray(values, dtype=float)
    return frame


def sample_starts(n: int, key: jax.Array) -> PompParameters:
    """``n`` dispersed chain starts, drawn uniformly from the prior box.

    Only the free parameters vary; the rest stay at their true values.
    """
    keys = jax.random.split(key, len(FREE))
    overrides = {}
    for k, name in zip(keys, FREE):
        lo, hi = PRIOR_BOX[name]
        overrides[name] = np.asarray(jax.random.uniform(k, (n,), minval=lo, maxval=hi))
    return params_from_frame(theta_frame(n, overrides))


def grid_frame(n_side: int) -> tuple[pd.DataFrame, np.ndarray, np.ndarray]:
    """A ``n_side x n_side`` lattice over the prior box, one row per point.

    Returns the frame plus the two 1-D axes, so the caller can chunk the rows
    and the report can reshape the flat log-likelihood vector into a surface.
    """
    lo_b, hi_b = PRIOR_BOX["beta1"]
    lo_r, hi_r = PRIOR_BOX["rho"]
    # Cell centres, so every evaluation sits strictly inside the box and the
    # quadrature is a midpoint rule.
    beta1_axis = np.linspace(lo_b, hi_b, n_side + 1)[:-1] + (hi_b - lo_b) / (2 * n_side)
    rho_axis = np.linspace(lo_r, hi_r, n_side + 1)[:-1] + (hi_r - lo_r) / (2 * n_side)
    bb, rr = np.meshgrid(beta1_axis, rho_axis, indexing="ij")
    frame = theta_frame(bb.size, {"beta1": bb.ravel(), "rho": rr.ravel()})
    return frame, beta1_axis, rho_axis


def sir_pomp(theta: PompParameters | None = None, with_prior: bool = True) -> pp.Pomp:
    """The benchmark Pomp: pypomp's SIR components over the committed dataset.

    Mirrors the tail of ``pypomp.models.sir.sir`` but substitutes the R-generated
    data for a fresh simulation.
    """
    ys = load_data()
    covars = precompute_bspline_covars(ys.index.values, T0)
    if theta is None:
        theta = params_from_frame(theta_frame(1))
    return pp.Pomp(
        ys=ys,
        theta=theta,
        statenames=STATENAMES,
        t0=T0,
        rinit=rinit,
        rproc=rproc,
        dmeas=dmeas,
        rmeas=rmeas,
        par_trans=ParTrans(to_est=to_est, from_est=from_est),
        nstep=NSTEP,
        accumvars=ACCUMVARS,
        covars=covars,
        dprior=sir_dprior if with_prior else None,
    )


def proposal() -> pp.MVNDiagRW:
    """The random-walk proposal, matching ``mvn_diag_rw(BAYES_RW_SD)`` in R."""
    return pp.MVNDiagRW(RW_SD)


#: ABC posteriors are 2-6x wider than the full posterior, so RW_SD left the
#: ABC chains with autocorrelation times of hundreds of iterations. Matches
#: BAYES_ABC_RW_SD in model.R by the same linearization.
ABC_RW_SD: dict[str, float] = {"beta1": 0.06, "rho": 0.15}


def abc_proposal() -> pp.MVNDiagRW:
    return pp.MVNDiagRW(ABC_RW_SD)


# --- ABC probes -------------------------------------------------------------
# Mean reports in each quarter of the year, pooled over years; twins of
# bayes_probes() in model.R. Binned by observation index so both languages agree
# exactly. These replaced mean/sd/acf1, which carry almost no information about
# beta1 (its ABC posterior was the prior).

N_YEARS = 4
N_QUARTERS = 4
WEEKS_PER_QUARTER = 13


def _quarter_means(y: dict[str, jax.Array]) -> jax.Array:
    blocks = y["reports"].reshape(N_YEARS, N_QUARTERS, WEEKS_PER_QUARTER)
    return jnp.mean(blocks, axis=(0, 2))


PROBES = {
    f"qtr{q + 1}": (lambda y, q=q: _quarter_means(y)[q]) for q in range(N_QUARTERS)
}

#: Shared by abc/run.py, abc/run.R and reference/run.py. The first rung accepts
#: everything, so its ABC posterior is the prior.
ABC_EPS_LADDER = (1e6, 4.0, 2.5, 1.5)


def abc_distance_fn(obj: pp.Pomp):
    """A jitted ``f(free, key)``: one fresh simulation per row of ``free`` (an
    ``(n, len(FREE))`` array), returning the squared scaled probe distances.

    Computed here rather than by pypomp's abc internals, so the rejection
    reference does not share the distance code it is checking.
    """
    struct = obj.to_struct()
    names = list(struct.param_names)
    truth = true_theta()
    base = jnp.asarray([truth[n] for n in names])
    idx = jnp.asarray([names.index(p) for p in FREE])
    scale = probe_scale()
    scale_arr = jnp.asarray([scale[p] for p in PROBES])
    obs = jnp.stack(
        [
            fn({"reports": jnp.asarray(load_data()["reports"].to_numpy(), dtype=float)})
            for fn in PROBES.values()
        ]
    )

    def probe_vec(reports):
        return jnp.stack([fn({"reports": reports}) for fn in PROBES.values()])

    @jax.jit
    def f(free, key):
        n = free.shape[0]
        thetas = jnp.tile(base, (n, 1)).at[:, idx].set(free)
        _, Y = pp.functional.simulate(struct, 1, thetas, keys=jax.random.split(key, n))
        sim = jax.vmap(probe_vec)(Y[:, 0, :, 0])
        return jnp.sum(((sim - obs) / scale_arr) ** 2, axis=1)

    return f


def probe_scale(path: str = SCALE_PATH) -> dict[str, float]:
    """Per-probe normalizing weights, as written by model.R."""
    df = pd.read_csv(path)
    return dict(zip(df["probe"], df["scale"].astype(float)))
