"""Shared definition of the SIR Bayesian benchmark for pypomp.

Import this from a kind directory (reference/, pmcmc/, abc/):

    import model

Paths below are relative to the kind directory, since the test runner cd's into
the directory of the script it is running. All kinds sit at the same depth, so
one path works for each.

The dataset is generated by R (see model.R) and read here, rather than letting
pypomp's ``sir()`` simulate its own. Both constructors simulate at build time
from different RNGs, so one side has to be the generator of record or nothing
downstream is comparable.
"""

import jax
import jax.numpy as jnp
import numpy as np
import pandas as pd
import pypomp as pp
import xarray as xr
from pypomp.core.par_trans import ParTrans
from pypomp.core.parameters import PompParameters
from pypomp.models.sir import (
    STATENAMES,
    dmeas,
    from_est,
    precompute_bspline_covars,
    rinit,
    rmeas,
    rproc,
    to_est,
)
from pypomp.types import ParamDict

MAIN_SEED = 3141593

#: The two estimated parameters. Everything else is fixed at its true value.
FREE = ("beta1", "rho")

#: Flat bounded priors, matching the Csnippet in model.R exactly.
#:
#: The width is set by what the grid reference can resolve, not by taste. A
#: level-1 scan of the likelihood surface puts the posterior sd near 11 for
#: beta1 and 0.019 for rho, so the box below spans roughly +/-9 posterior sd in
#: each direction: wide enough that the flat-prior truncation is irrelevant and
#: that chains started from the prior are genuinely dispersed, tight enough that
#: a 60x60 grid gives about three cells per posterior sd. An earlier, much wider
#: box gave barely one cell per sd, which is too coarse to serve as a reference.
PRIOR_BOX: dict[str, tuple[float, float]] = {
    "beta1": (300.0, 500.0),
    "rho": (0.45, 0.80),
}

#: Random-walk proposal scales, on the ESTIMATION scale -- log for beta1, logit
#: for rho, per pypomp.models.sir.to_est.
#:
#: This is measured, not assumed. pypomp's pmcmc runs the chain on the
#: transformed scale: an rw_sd of 0.05 moves beta1 by about +/-20 around 400
#: (= 400*exp(0.05)), while an rw_sd of 10 moves it not at all, because
#: 400*exp(+/-10) lands outside the prior box and is rejected every time.
#: dprior, the traces, and PompParameters are all on the natural scale; only the
#: proposal is transformed.
#:
#: Consequence: this is NOT interchangeable with the natural-scale rw.sd that
#: R's mvn_diag_rw takes. model.R carries the local-linearization image of these
#: numbers so the two kernels are comparably efficient -- but they are different
#: kernels, both valid, and only their stationary distributions are compared.
RW_SD: dict[str, float] = {"beta1": 0.02, "rho": 0.05}

DATA_PATH = "../data/sir_data.csv"
TRUE_PATH = "../data/true_theta.csv"
SCALE_PATH = "../data/probe_scale.csv"

T0 = 0.0
NSTEP = 20
ACCUMVARS = ("cases", "logw")


def load_data(path: str = DATA_PATH) -> pd.DataFrame:
    """The canonical dataset, indexed by observation time."""
    return pd.read_csv(path).set_index("time")


def true_theta(path: str = TRUE_PATH) -> dict[str, float]:
    """The simulating parameters, as written by model.R."""
    df = pd.read_csv(path)
    return dict(zip(df["parameter"], df["value"].astype(float)))


def sir_dprior(params: ParamDict) -> float:
    """Log-density of the flat box prior on ``beta1`` and ``rho``.

    Normalized inside the box and ``-inf`` outside, so proposals leaving the box
    are rejected.

    pypomp hands this function natural-scale values, the same contract as pomp's
    dprior Csnippet, which is what lets the two be written identically. Measured
    rather than assumed: with the box below, pmcmc reports a log_prior of exactly
    -log(hi_b - lo_b) - log(hi_r - lo_r) at the true theta, with no Jacobian term
    added. Note this is a *different* scale from the one the proposal works on --
    see the note on RW_SD above.
    """
    lo_b, hi_b = PRIOR_BOX["beta1"]
    lo_r, hi_r = PRIOR_BOX["rho"]
    inside = (
        (params["beta1"] > lo_b)
        & (params["beta1"] < hi_b)
        & (params["rho"] > lo_r)
        & (params["rho"] < hi_r)
    )
    log_dens = -jnp.log(hi_b - lo_b) - jnp.log(hi_r - lo_r)
    return jnp.where(inside, log_dens, -jnp.inf)


def params_from_frame(rows: pd.DataFrame) -> PompParameters:
    """A replicate-indexed PompParameters from one row per chain/grid point."""
    names = list(rows.columns)
    arr = np.expand_dims(rows.to_numpy(dtype=float), axis=1)  # (n, 1, p)
    da = xr.DataArray(
        arr,
        dims=["theta_idx", "unit", "parameter"],
        coords={
            "theta_idx": np.arange(len(rows)),
            "unit": ["shared"],
            "parameter": names,
        },
    )
    return PompParameters(da)


def theta_frame(n: int, overrides: dict[str, np.ndarray] | None = None) -> pd.DataFrame:
    """``n`` copies of the true parameter vector, with ``overrides`` applied."""
    base = true_theta()
    frame = pd.DataFrame([base] * n).reset_index(drop=True)
    for name, values in (overrides or {}).items():
        frame[name] = np.asarray(values, dtype=float)
    return frame


def sample_starts(n: int, key: jax.Array) -> PompParameters:
    """``n`` dispersed chain starts, drawn uniformly from the prior box.

    Only the free parameters vary; the rest stay at their true values.
    """
    keys = jax.random.split(key, len(FREE))
    overrides = {}
    for k, name in zip(keys, FREE):
        lo, hi = PRIOR_BOX[name]
        overrides[name] = np.asarray(jax.random.uniform(k, (n,), minval=lo, maxval=hi))
    return params_from_frame(theta_frame(n, overrides))


def grid_frame(n_side: int) -> tuple[pd.DataFrame, np.ndarray, np.ndarray]:
    """A ``n_side x n_side`` lattice over the prior box, one row per point.

    Returns the frame plus the two 1-D axes, so the caller can chunk the rows
    and the report can reshape the flat log-likelihood vector into a surface.
    """
    lo_b, hi_b = PRIOR_BOX["beta1"]
    lo_r, hi_r = PRIOR_BOX["rho"]
    # Cell centres, so every evaluation sits strictly inside the box and the
    # quadrature is a midpoint rule.
    beta1_axis = np.linspace(lo_b, hi_b, n_side + 1)[:-1] + (hi_b - lo_b) / (2 * n_side)
    rho_axis = np.linspace(lo_r, hi_r, n_side + 1)[:-1] + (hi_r - lo_r) / (2 * n_side)
    bb, rr = np.meshgrid(beta1_axis, rho_axis, indexing="ij")
    frame = theta_frame(bb.size, {"beta1": bb.ravel(), "rho": rr.ravel()})
    return frame, beta1_axis, rho_axis


def sir_pomp(theta: PompParameters | None = None, with_prior: bool = True) -> pp.Pomp:
    """The benchmark Pomp: pypomp's SIR components over the committed dataset.

    Mirrors the tail of ``pypomp.models.sir.sir`` but substitutes the R-generated
    data for a fresh simulation.
    """
    ys = load_data()
    covars = precompute_bspline_covars(ys.index.values, T0)
    if theta is None:
        theta = params_from_frame(theta_frame(1))
    return pp.Pomp(
        ys=ys,
        theta=theta,
        statenames=STATENAMES,
        t0=T0,
        rinit=rinit,
        rproc=rproc,
        dmeas=dmeas,
        rmeas=rmeas,
        par_trans=ParTrans(to_est=to_est, from_est=from_est),
        nstep=NSTEP,
        accumvars=ACCUMVARS,
        covars=covars,
        dprior=sir_dprior if with_prior else None,
    )


def proposal() -> pp.MVNDiagRW:
    """The random-walk proposal, matching ``mvn_diag_rw(BAYES_RW_SD)`` in R."""
    return pp.MVNDiagRW(RW_SD)


# --- ABC probes -------------------------------------------------------------
# Pure-JAX twins of bayes_probes() in model.R. probe_acf in particular
# dispatches to a C routine in pomp whose centring and divisor conventions are
# not safe to assume, so abc/report.qmd checks these numerically against the R
# values before any ABC run is interpreted.


def probe_mean(y: dict[str, jax.Array]) -> jax.Array:
    return jnp.mean(y["reports"])


def probe_sd(y: dict[str, jax.Array]) -> jax.Array:
    return jnp.std(y["reports"], ddof=1)


def probe_acf1(y: dict[str, jax.Array]) -> jax.Array:
    """Lag-1 autocorrelation of the centred series, in pomp's convention.

    pomp's ``probe_acf(type="correlation")`` is not ``stats::acf``: it carries an
    n/(n-1) small-sample correction. Measured on the committed dataset, pomp
    returns 0.8430387 where ``stats::acf`` and the uncorrected ratio both return
    0.8389856, and 0.8389856 * 208/207 = 0.8430385. The factor below is that
    correction, and abc/report.qmd re-checks the agreement numerically rather
    than trusting this comment.
    """
    x = y["reports"] - jnp.mean(y["reports"])
    n = x.shape[0]
    return (n / (n - 1)) * jnp.sum(x[1:] * x[:-1]) / jnp.sum(x * x)


PROBES = {"mean": probe_mean, "sd": probe_sd, "acf1": probe_acf1}


def probe_scale(path: str = SCALE_PATH) -> dict[str, float]:
    """Per-probe normalizing weights, as written by model.R."""
    df = pd.read_csv(path)
    return dict(zip(df["probe"], df["scale"].astype(float)))
